### ISSUE TITLE
Bottom Tiles Arrangement

### ISSUE THREAD

**Issue by jonecat** [edgepointlearning/edgepointlearning.github.io#36]
The following pages should have only 2 tiles at the bottom and the home page should keep the 4 current ones it has.

**Learning Solutions**

- Check Out Our Demos
- Let's Talk

**Success Stories - Main**

- Check Out Our Demos
- Let's Talk

**Individual Success Stories**

- Check Out Our Demos
- Let's Talk

**Blog - Main**

- Let's Talk
- Subscribe to Our Newsletter!

**Individual Blog Posts**

- Let's Talk
- Subscribe to Our Newsletter!

**About**

- Check Out Our Demos
- Subscribe to Our Newsletter!

**Contact Us**
None

**Comment by tylercampbell** [comment]
b089fd1

**Comment by jonecat** [comment]
Demo Form Success Page
Let's Talk
Subscribe to Our Newsletter!

Let's Talk Success Page
Subscribe to Our Newsletter!
Check Out Our Demos

Newsletter Success Page
Let's Talk
Check Out Our Demos
