### ISSUE TITLE
Custom 404 page with a monkey

### ISSUE THREAD

**Issue by jonecat** [edgepointlearning/edgepointlearning.github.io#40]
We need to work on this

**Comment by jonecat** [comment]
![screen shot 2016-07-20 at 3 41 44 pm](https://cloud.githubusercontent.com/assets/16053394/17005755/c07afdc8-4e90-11e6-9ec8-2db8f89ea91e.png)
Just a thought on a potential treatment

**Comment by tylercampbell** [comment]
http://www.thinkstockphotos.com/image/stock-photo-chimpanzee-at-an-office-desk/57564963
